from mxnet import nd

In [5]:
x = nd.arange(12)

In [6]:
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [7]:
x.shape

(12,)

In [8]:
x.reshape((3,4))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [9]:
x.reshape((-1,4))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [10]:
x.reshape((3,-1))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [11]:
nd.zeros((2, 3, 4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [12]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [13]:
nd.random.normal(0,1,shape=(3,4))


[[ 1.1630787   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.5580711  -0.5459446  -2.3556297 ]
 [ 0.5414402   2.6785066   1.2546344  -0.54877394]]
<NDArray 3x4 @cpu(0)>

### 广播机制

In [14]:
A = nd.arange(3).reshape((3,1))
B = nd.arange(2).reshape((1,2))
print(A)
print(B)


[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>

[[0. 1.]]
<NDArray 1x2 @cpu(0)>


In [15]:
A + B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [16]:
A*B


[[0. 0.]
 [0. 1.]
 [0. 2.]]
<NDArray 3x2 @cpu(0)>

In [17]:
A/B


[[nan  0.]
 [inf  1.]
 [inf  2.]]
<NDArray 3x2 @cpu(0)>

In [19]:
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [22]:
y = nd.array([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

In [23]:
y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

### 运算

In [25]:
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [27]:
X = x.reshape((3,4))

In [28]:
X+y


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [29]:
X/y


[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>

In [31]:
y.exp() #指数运算


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

In [32]:
nd.dot(X,y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [33]:
# 矩阵🔗 🔗的纬度进行相加

In [34]:
nd.concat(X,y,dim=0) # 纵向连接


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
<NDArray 6x4 @cpu(0)>

In [36]:
nd.concat(X,y,dim=1) # 横向连接


[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]
<NDArray 3x8 @cpu(0)>

In [37]:
X==y


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [38]:
X.sum()


[66.]
<NDArray 1 @cpu(0)>

In [39]:
X.norm()


[22.494442]
<NDArray 1 @cpu(0)>

In [40]:
X.norm().asscalar()

22.494442

In [41]:
before = id(y)
y = y+X
id(y) == before

False

In [44]:
z = y.zeros_like()
before = id(z)
z[:] = X+y
id(z) == before

True

In [45]:
nd.elemwise_add(X,y,out=z)


[[ 2.  3.  8.  9.]
 [ 9. 12. 15. 18.]
 [20. 21. 22. 23.]]
<NDArray 3x4 @cpu(0)>

In [46]:
id(z) == before

True

### NDArray  Numpy

In [47]:
import numpy as np

In [49]:
P = np.ones((2,3))
D = nd.array(P)

In [50]:
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [51]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

#### 自动求梯度

In [52]:
from mxnet import autograd,nd

In [53]:
# 对函数y = 2x*xT 求关于列向量x的梯度

In [54]:
x = nd.arange(4).reshape(4,-1)

In [55]:
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [56]:
x.attach_grad()

In [57]:
# 使用record 函数来记录 求梯度相关的计算

In [58]:
with autograd.record():
    y = 2*nd.dot(x.T,x)

In [59]:
y.backward()

In [60]:
assert (x.grad - 4*x).norm().asscalar() ==0 

In [62]:
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

##### 对python控制流求梯度

In [69]:
def f(a):
    b = a*2
    while b.norm().asscalar() < 1000:
        b = b*2
    if b.sum().asscalar() > 0:
        c = b
    else:
        c = 100 *b
    return c

In [70]:
a = nd.random.normal(shape=1)
a.attach_grad()

with autograd.record():
    c = f(a)
c.backward()

In [71]:
a.grad == c/a


[1.]
<NDArray 1 @cpu(0)>